In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running th is (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pima-indians-diabetes-database/diabetes.csv


In [2]:
df =pd.read_csv("/kaggle/input/pima-indians-diabetes-database/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df.shape

(768, 9)

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [6]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

## Scale Data First

In [7]:
from sklearn.preprocessing import StandardScaler
scaler =StandardScaler()

In [8]:
X=scaler.fit_transform(X)

In [9]:
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [11]:
X_test

array([[ 0.93691372,  0.47275805,  0.25303625, ..., -0.76057349,
         0.52889435,  1.51108316],
       [-0.84488505,  0.94221523, -0.47073225, ..., -0.74788157,
        -0.88452119, -0.95646168],
       [ 0.63994726, -0.37226487, -0.47073225, ..., -0.88749274,
        -0.80297799, -0.53102292],
       ...,
       [ 1.23388019,  2.10020961,  0.45982725, ...,  2.01895798,
        -1.01136617,  0.83038113],
       [ 0.3429808 ,  0.47275805,  0.66661825, ..., -4.06047387,
         0.50775352,  3.04266271],
       [ 0.04601433, -0.96691063, -3.57259724, ..., -0.506735  ,
         0.41714996, -0.19067191]])

In [12]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so: undefined symbol: _ZN3tsl6StatusC1EN10tensorflow5error4CodeESt17basic_string_viewIcSt11char_traitsIcEENS_14SourceLocationE']
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/opt/conda/lib/python3.10/site-packages/tensorflow_io/python/ops/libtensorflow_io.so: undefined symbol: _ZTVN10tenso

## Train first Version on Model

In [13]:
model=Sequential()
#hidden layer
model.add(Dense(32,activation='relu',input_dim=8))
#output layer
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 [==============================] - 1s 14ms/step - loss: 0.7860 - accuracy: 0.3550 - val_loss: 0.7592 - val_accuracy: 0.3701
Epoch 2/100
20/20 [==============================] - 0s 3ms/step - loss: 0.7103 - accuracy: 0.4919 - val_loss: 0.6954 - val_accuracy: 0.5519
Epoch 3/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6544 - accuracy: 0.6498 - val_loss: 0.6461 - val_accuracy: 0.6364
Epoch 4/100
20/20 [==============================] - 0s 3ms/step - loss: 0.6151 - accuracy: 0.7036 - val_loss: 0.6110 - val_accuracy: 0.7273
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5851 - accuracy: 0.7394 - val_loss: 0.5848 - val_accuracy: 0.7532
Epoch 6/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5625 - accuracy: 0.7476 - val_loss: 0.5627 - val_accuracy: 0.7662
Epoch 7/100
20/20 [==============================] - 0s 3ms/step - loss: 0.5439 - accuracy: 0.7573 - val_loss: 0.5448 - val_accuracy: 0.7727
Epoch 8/100


### Plan
1. How to select appropriate optimizer
2. No of nodes in layer
3. How to Select no of layers
4. All in one model

## How to select appropriate optimizer

In [16]:
import kerastuner as kt

/tmp/ipykernel_33/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt


In [17]:
#First create first Function
def build_model(hp): #hp:hyperparameter
    model=Sequential()
    #hidden layer
    model.add(Dense(32,activation='relu',input_dim=8))
    #output layer
    model.add(Dense(1,activation='sigmoid'))
    #make list of available optimizers
    optimizers=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta'])
    
    model.compile(optimizer=optimizers,loss='binary_crossentropy',metrics=['accuracy'])
    return model
    

In [18]:
#The code snippet defines a tuner object using Keras Tuner's RandomSearch algorithm to search for the best hyperparameters for a model. 
#The objective is to maximize validation accuracy, and the tuner will explore up to 5 different combinations of hyperparameters.
tuner=kt.RandomSearch(build_model,
                     objective='val_accuracy',
                     max_trials=5)

In [19]:
#The code performs a hyperparameter search using a tuner on the training data for a maximum of 5 epochs, while validating the model's performance on the test data.
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7922077775001526

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 06s


In [20]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

We got Adam as best optimizer

In [25]:
#This code retrieves the best model from a tuner, which likely performs hyperparameter optimization. 
#The "num_models=1" argument specifies that only one model is requested, and "[0]" indexes the first (and presumably best) model from the returned list.
model=tuner.get_best_models(num_models=1)[0]

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 321
Trainable params: 321
Non-trainable params: 0
_________________________________________________________________


In [32]:
#It starts from epoch 6 and validates the model's performance using the test data X_test and y_test
model.fit(X_train,y_train,batch_size=32,initial_epoch=6,validation_data=(X_test,y_test))

## How to find No of nodes in layer